name: "Docker build setup"

runs:
  using: "composite"
  steps:

    - name: setup docker context for buildx
      id: buildx-context
      shell: bash
      run: docker context create builders

    - name: setup docker buildx
      uses: crazy-max/docker-setup-buildx-action@fix-dl-release
      with:
        endpoint: builders
        version: v0.8.2

    - uses: imjasonh/setup-crane@5146f708a817ea23476677995bf2133943b9be0b # pin@v0.1

