name: "Sample reuse workflow"

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      GIT_SHA:
        required: true
        type: string
        description: The git SHA1 to build. If not specified, the latest commit on the triggering branch will be built


jobs:
  rust-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          ref: ${{ inputs.GIT_SHA }}

      - run: |
          echo "Hello, world! THIS IS TEST1"
          echo "The current SHA is ${{ inputs.GIT_SHA }}"
