name: "Test docker-setup"

on:
  push:

permissions:
  contents: read

jobs:
  run-docker-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          path: actions

      - uses: ./actions/docker-setup
