name: "main-workflow"
on:
  # Allow triggering manually
  workflow_dispatch:
    inputs:
      GIT_SHA:
        required: true
        type: string
        description: The git SHA1 to test. If not specified, it will use the latest commit on main.
  # TODO: delete this
  workflow_call:
    inputs:
      GIT_SHA:
        required: true
        type: string
        description: The git SHA1 to test. If not specified, it will use the latest commit on main.
  pull_request:

# cancel redundant builds
concurrency:
  # cancel redundant builds on PRs (only on PR, not on branches)
  group: ${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.ref) || github.sha }}
  cancel-in-progress: true

jobs:
  determine-test-metadata:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.determine-test-image-tag.outputs.IMAGE_TAG }}
      BRANCH: ${{ steps.determine-test-branch.outputs.BRANCH }}
    steps:
      - name: Determine branch based on cadence
        id: determine-test-branch
        run: |
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            if [[ "${{ github.event.schedule }}" == "0 9 * * *" ]]; then
              echo "Branch: main"
              echo "BRANCH=main" >> $GITHUB_OUTPUT
            elif [[ "${{ github.event.schedule }}" == "0 21 * * *" ]]; then
              echo "Branch: quorum-store"
              echo "BRANCH=quorum-store" >> $GITHUB_OUTPUT
            else
              echo "Unknown schedule: ${{ github.event.schedule }}"
              exit 1
            fi
          else
            echo "Branch: main"
            echo "BRANCH=main" >> $GITHUB_OUTPUT
            cat $GITHUB_OUTPUT
          fi
      - name: print output
        run: echo ${{ steps.determine-test-branch.outputs.BRANCH }}


  test-reuse-workflow:
    needs: determine-test-metadata
    uses: ./.github/workflows/reuse-workflow.yaml
    secrets: inherit
    with:
      BOOLEAN_FOR_SOMETHING: ${{ contains('main', needs.determine-test-metadata.outputs.BRANCH) }} 
      BOOLEAN_FOR_SOMETHING_2: ${{ 'main' == needs.determine-test-metadata.outputs.BRANCH }}
      DETERMINED_BRANCH: ${{ needs.determine-test-metadata.outputs.BRANCH }}
      BRANCH: 'main'
      TIMEOUT_MINUTES: 10
