name: "replay-verify"
on:
  # Allow triggering manually
  workflow_dispatch:
    inputs:
      GIT_SHA:
        required: true
        type: string
        description: The git SHA1 to test. If not specified, it will use the latest commit on main.
  # TODO: delete this
  workflow_call:
    inputs:
      GIT_SHA:
        required: true
        type: string
        description: The git SHA1 to test. If not specified, it will use the latest commit on main.

# cancel redundant builds
concurrency:
  # cancel redundant builds on PRs (only on PR, not on branches)
  group: ${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.ref) || github.sha }}
  cancel-in-progress: true

jobs:
  test-reuse-workflow:
    uses: ./.github/workflows/reuse-workflow.yaml
    secrets: inherit
    with:
      GIT_SHA: ${{ inputs.GIT_SHA }}
